### ISSUE TITLE
Make the latest version available on command line

### ISSUE THREAD

**Issue by fgrelard** [AlanRace/imzMLConverter#1]
It seems the [GUI version](https://www.cs.bham.ac.uk/~ibs/imzMLConverter/) does not use quite the same code as what is available in this repository. 

I convert mzML produced by msconvert. The GUI version is able to produce a correct imzML output, supplying both the image dimensions, and a file with spectre positions. However, supplying both inputs is not allowed in the command line version. Moreover, it looks for "scan start date" tags in the mzML file and produces a fatal error if it is not present. 

Would it be possible to update this repo with the currently used version in the GUI?

**Comment by AlanRace** [comment]
Can you be more specific with the command you are using to convert with the command line? You shouldn't need to specify the image dimensions if you are supplying a file with the coordinates. What type of data are you trying to convert? And what type of coordinates file are you using?

**Comment by fgrelard** [comment]
Thanks for your answer @AlanRace. 
I am trying to convert Bruker data to imzML. I am using Proteowizard's `msconvert` to convert Bruker data to mzML, and then your tool from mzML to imzML, as described in [this document](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiihLb1u9HhAhWC6uAKHd7yCPgQFjAAegQIARAC&url=https%3A%2F%2Fwww.shimadzu.com%2Fan%2Flifescience%2Fimaging%2Freveal%2FMaking_imzML_fromVariousTypeOfFiles.pdf&usg=AOvVaw1V3dkMTEZ0wSyue3hdKkcf).

I obtain a single mzML file containing all the spectres. Here is the command I use to convert from mzML to imzML:
```bash
java -jar .\jimzMLConverter-2.0.5.jar imzML path\to\file.mzML -o path\to\file -p path\to\list.txt
```
where `list.txt` is a file with spectre positions formatted by `x y z` coordinates and separated by line breaks. This file is correctly interpreted by the GUI version.

The command above throws an exception:
```java
Exception in thread "main" java.lang.NullPointerException  
at com.alanmrace.jimzmlconverter.MzMLToImzMLConverter.getNumberSpectraPerPixel(MzMLToImzMLConverter.java:215)                                                              
at com.alanmrace.jimzmlconverter.MzMLToImzMLConverter.generatePixelLocations(MzMLToImzMLConverter.java:92)                                                                  
at com.alanmrace.jimzmlconverter.ImzMLConverter.convert(ImzMLConverter.java:364)                                                                                           
at com.alanmrace.jimzmlconverter.MzMLToImzMLConverter.convert(MzMLToImzMLConverter.java:260)                                                                               
at com.alanmrace.jimzmlconverter.MainCommand.convert(MainCommand.java:452)           
at com.alanmrace.jimzmlconverter.MainCommand.main(MainCommand.java:187)
```
And before that, fails to recognize some tags: 
```java
INFOS: Unknown value-type encountered 'value-type:xsd\:dateTime "The allowed value-type for this CV term."' @ MS:1000747
```
I tried delving a bit into the code, and the exception is not thrown when I manually add the following tag as a node of `<scan>` in the mzML file:
```xml
<cvParam cvRef="MS" accession="MS:1000016" name="scan start time" unitAccession="UO:0000031" unitCvRef="MS" unitName="minute" value="0.046866666666666668" />
```
I don't know if that helps.

Anyway, here is a minimal example for you to try for yourself:
[Sample_mini.zip](https://github.com/AlanRace/imzMLConverter/files/3078827/Sample_mini.zip)

**Comment by AlanRace** [comment]
Thanks for the detailed description. The warning about the unknown value-type is unrelated to the issue you were experiencing, but thanks for pointing it out.

Your main issue should be resolved in https://github.com/AlanRace/imzMLConverter/commit/5c95412f8c03c24111fde42f2b6a91c909219c35 which is now part of version 2.0.6 (https://github.com/AlanRace/imzMLConverter/releases/tag/2.0.6)
